// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using budget_backend.data;

#nullable disable

namespace budget_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220320081707_New-Types")]
    partial class NewTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("budget_backend.data.dbDto.AccountDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("budget_backend.data.dbDto.AccountEntryDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Timestamp")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AccountEntries");
                });

            modelBuilder.Entity("budget_backend.data.dbDto.AccountTransactionDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountEntryIdFrom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountEntryIdTo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountIdFrom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountIdTo")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Timestamp")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("budget_backend.data.dbDto.BudgetaryItemDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BudgetaryItems");
                });

            modelBuilder.Entity("budget_backend.data.dbDto.BudgetEntryDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BudgetaryItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Month")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BudgetEntries");
                });

            modelBuilder.Entity("budget_backend.data.dbDto.SpendingDto", b =>
                {
                    b.Property<Guid>("AccountEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetaryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountEntryId", "BudgetaryItemId");

                    b.ToTable("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
