name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
  # trigger manually
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  backend-build-and-test:

    name: build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./backend/
      run: dotnet restore
      
    - name: Build
      working-directory: ./backend/
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ./backend/
      run: dotnet test --no-restore --verbosity normal
