name: Docker Image CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # trigger manually
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./backend/
        file: ./Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/schlemmerservice-backend:latest
