name: Docker Image CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # trigger manually
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./backend --file Dockerfile --tag budget-backend:$(date +%s)
